(() => {
  const translations = {
  "I'm Hansheng Tian. Explore my years in VEX robotics, science projects, love of sports, and interest in psychology.": "我是田翰声。这里记录了我的 VEX 机器人经历、科学项目、运动爱好，以及对心理学的探索。",
  "Home | Hansheng Tian": "首页 | 田翰声",
  "Skip to content": "跳转到正文",
  "Hansheng Tian home": "田翰声的首页",
  "Main navigation": "主导航",
  "About": "关于我",
  "Robotics": "机器人",
  "Project": "项目",
  "Beyond Robotics": "机器人之外",
  "Psychology & Community": "心理与社区",
  "Hansheng": "田",
  "Tian.": "翰声",
  "I’m a student who loves building robots, exploring science, and staying active.": "我是一名热爱搭建机器人、探索科学和运动的学生。",
  "I want to use what I learn to understand people better and help those around me.": "我希望用所学更好地理解他人，帮助身边的人。",
  "Always curious. Always becoming.": "始终好奇，不断成长。",
  "Close photo": "关闭照片",
  "Close": "关闭",
  "Zoom out": "缩小",
  "Zoom in": "放大",
  "About | Hansheng Tian": "关于我 | 田翰声",
  "ABOUT": "关于我",
  "Room for more": "兴趣不止一种，",
  "than one interest.": "探索不设边界。",
  "I’m Hansheng Tian, a student at Beijing Sanfan Middle School. Robotics has been part of my life for years, but there is much more I want to explore.": "我是田翰声，来自北京市三帆中学。机器人已经陪伴我多年，而我想探索的远不止这些。",
  "I’m curious about how things work and how people think. I like turning questions into experiments, staying active through sports, and sharing what I learn with other people.": "我好奇事物如何运作，也好奇人们如何思考。我喜欢把问题变成实验，在运动中保持活力，也把学到的知识分享给别人。",
  "VEX has given me something to keep working at over many seasons. Science projects let me try out ideas that might help people around me. Sport, magic, and psychology give me other ways to learn and connect.": "多个赛季的 VEX 经历，让我学会在一件事上持续投入。科学项目让我尝试用自己的想法帮助身边的人。运动、魔术和心理学，则带给我不同的学习与交流方式。",
  "This is a collection of the things I’m working on, learning from, and growing into.": "这里记录了我正在做的事、学到的知识，以及成长中的点滴。",
  "Hansheng at his robotics workbench": "田翰声在机器人工作台前",
  "At the workbench · Beijing, China": "在工作台前 · 中国北京",
  "Hansheng Tian": "田翰声",
  "Home": "首页",
  "Psychology & Community | Hansheng Tian": "心理与社区 | 田翰声",
  "03 / UNDERSTANDING PEOPLE": "03 / 理解他人",
  "Learning": "学习",
  "to listen.": "倾听。",
  "My interest in psychology connects to a simple question: how can we understand one another better?": "我对心理学的兴趣，源于一个简单的问题：我们怎样才能更好地理解彼此？",
  "A classroom mini-lesson on listening, led in my role as class psychology representative.": "作为班级心理委员，我主持了一堂关于倾听的心理小讲堂。",
  "Enlarge classroom listening lesson": "放大倾听小讲堂照片",
  "Hansheng presenting a classroom lesson about listening": "田翰声在课堂上讲解倾听",
  "A psychology mini-lesson on listening": "关于倾听的心理小讲堂",
  "CLASS PSYCHOLOGY REPRESENTATIVE": "班级心理委员",
  "Psychology in": "把心理学带进",
  "our classroom.": "我们的课堂。",
  "As my class’s psychology representative, I led a mini-lesson about listening and communication.": "作为班级心理委员，我主持了一次关于倾听和沟通的心理小讲堂。",
  "We used a message-passing activity: one student reads a sentence, then whispers it to the next person. It gave us a concrete way to explore how information can change as it travels.": "我们做了一个传话游戏：一位同学读完一句话，再小声传给下一位同学。这个活动让我们直观地看到，信息在传递过程中会怎样变化。",
  "I want to keep learning about psychology and use that knowledge to contribute to my school community.": "我希望继续学习心理学，用这些知识为学校和同学们做一些事。",
  "Introducing the message-passing exercise during the psychology mini-lesson.": "在心理小讲堂上介绍传话游戏。",
  "See the classroom activity": "查看课堂活动",
  "At the final evaluation of Beijing's 2025 environmental education activities for primary and secondary school students.": "在 2025 年北京市中小学生环境教育系列活动终评现场。",
  "Enlarge environmental education event photo": "放大环境教育活动照片",
  "Hansheng on stage in front of the 2025 Beijing student environmental education final evaluation backdrop": "田翰声站在 2025 年北京市中小学生环境教育系列活动终评的舞台上",
  "PUBLIC SPEAKING / 2025": "演讲 / 2025",
  "Speaking up for the environment.": "为环境发声。",
  "I gave a talk at the final evaluation of Beijing's 2025 environmental education activities for primary and secondary school students.": "我在 2025 年北京市中小学生环境教育系列活动终评中进行了演讲。",
  "It was a chance to share my interest in environmental science with others.": "这让我有机会与更多人分享自己对环境科学的兴趣。",
  "A group photograph from the 2025 Beijing student environmental education event.": "2025 年北京市中小学生环境教育活动合照。",
  "See the event group photo": "查看活动合照",
  "Engineering Notebooks | Hansheng Tian": "工程笔记 | 田翰声",
  "Back to Robotics": "返回机器人页面",
  "Engineering Notebook": "工程笔记",
  "Choose a notebook": "选择一本笔记",
  "Previous page": "上一页",
  "Page": "页码",
  "Go to page": "跳转到指定页",
  "Next page": "下一页",
  "Enlarge current notebook page": "放大当前笔记页",
  "This page could not load.": "这一页暂时无法加载。",
  "Try again": "重试",
  "Enlarge page": "放大本页",
  "Use the page buttons or your keyboard’s left and right keys. Select the image to enlarge it. Original handwritten pages are shown in their original language.": "使用翻页按钮或键盘左右方向键浏览，点击图片可放大。手写笔记保留原文。",
  "Please enable JavaScript to use the notebook reader.": "请启用 JavaScript，以使用笔记阅读器。",
  "Project | Hansheng Tian": "项目 | 田翰声",
  "02 / QUESTIONS INTO PROJECTS": "02 / 从问题到项目",
  "What if I": "如果我能",
  "could make it?": "把它做出来呢？",
  "I want to use what I learn to help people around me. These projects began with questions about everyday life.": "我希望用所学帮助身边的人。这些项目，都从日常生活中的一个问题开始。",
  "Hansheng demonstrating his plant-care robot with two mechanical arms": "田翰声展示他的双机械臂植物养护机器人",
  "2025 / ROBOTICS": "2025 / 机器人",
  "PROJECT 01": "项目 01",
  "A robot to": "让机器人",
  "look after plants.": "照顾植物。",
  "When my family travelled, we asked my grandparents to care for our plants. I wondered whether a robot could help.": "家里出门旅行时，我们会请爷爷奶奶帮忙照顾植物。我想，机器人能不能帮上忙？",
  "I worked on a mobile plant-care robot with two mechanical arms, a soil-moisture sensor, and a watering system.": "我尝试制作一台移动式植物养护机器人，配备双机械臂、土壤湿度传感器和浇水系统。",
  "ESP32-S3 · K210 vision · 3D printing · AprilTag": "ESP32-S3 · K210 视觉 · 3D 打印 · AprilTag",
  "Read the project story": "阅读项目故事",
  "Start with the need": "从需求出发",
  "I collected 99 questionnaire responses about plant care and explored what people needed while away from home.": "我收集了 99 份植物养护问卷，了解人们出门在外时的养护需求。",
  "Build and test": "搭建与测试",
  "I combined a purchased four-wheel base and open-source arm designs with components I modelled and 3D printed, including a soil-loosening tool. I photographed and labelled plants for a recognition model, connected sensors and motors, and worked on the control program.": "我把购买的四轮底盘、开源机械臂设计，与自己建模和 3D 打印的部件组合起来，其中包括松土工具。我拍摄并标注植物照片，用于训练识别模型，同时连接传感器和电机，编写控制程序。",
  "Change the approach": "调整方法",
  "Recognising the plants directly was unreliable under different conditions. Adding AprilTag markers to the pots made locating them more dependable. I also adjusted the arm design and movement angles after testing.": "在不同环境下，直接识别植物的效果不够稳定。为花盆添加 AprilTag 标记后，定位变得更可靠。我也根据测试结果调整了机械臂的设计和运动角度。",
  "What comes next": "下一步",
  "I want to improve recognition in different lighting and move beyond manually starting each care cycle.": "我希望改善不同光照条件下的识别效果，并让养护流程不再需要每次手动启动。",
  "Hansheng presenting his autonomous catkin-cleaning robot": "田翰声展示他的自主杨柳絮清扫机器人",
  "2026 / ROBOTICS": "2026 / 机器人",
  "PROJECT 02": "项目 02",
  "Keeping flying": "让飞扬的杨柳絮",
  "fluff on the ground.": "留在地面。",
  "Springtime catkins can scatter again as they are swept. I explored a robot that brings spraying and collection together.": "春天的杨柳絮在清扫时容易再次飞散。我尝试把喷水和收集结合在一台机器人上。",
  "A camera locates the target, the robot approaches it, and a water spray helps keep the fluff in place for the brush to collect.": "摄像头定位目标后，机器人靠近并喷水，让杨柳絮留在原处，再用刷子收集。",
  "ESP32 · MaixCAM · Computer vision · Mechanical design": "ESP32 · MaixCAM · 计算机视觉 · 机械设计",
  "The idea": "项目想法",
  "Combine wetting and immediate sweeping in one small robot, rather than treating them as separate steps.": "让一台小型机器人连续完成湿润和清扫两个步骤。",
  "How it works": "工作原理",
  "The camera tracks the target while a servo adjusts its viewing angle. As the robot approaches, it activates the spray and brush. The prototype brings together a water tank, pump, nozzle, collection box, and sensors.": "摄像头跟踪目标，舵机调整视角。机器人靠近目标时启动喷水和刷子。原型整合了水箱、水泵、喷嘴、收集箱和传感器。",
  "Next questions": "接下来要探索的问题",
  "How well can it work when the lighting changes? How could battery life and collection capacity improve? These are areas for further testing and development.": "光照变化时，它还能稳定工作吗？续航和收集容量怎样提升？这些都需要进一步测试和改进。",
  "The phone assistant workflow: screenshot, page understanding, risk check, clear guidance": "手机助手流程：截图、理解页面、判断风险、提供清晰指引",
  "PHONE SCREEN ASSISTANT": "手机界面助手",
  "A confusing screen": "让人困惑的页面",
  "Upload a screenshot": "上传一张截图",
  "Understand the page": "理解页面",
  "Read the text and interface": "识别文字与界面",
  "Check the risk": "判断风险",
  "Permissions, ads, payments, or routine tasks": "权限、广告、支付或日常操作",
  "THE GOAL": "目标",
  "A clearer explanation.": "解释更清楚，",
  "A more informed next step.": "下一步更有把握。",
  "2026 / AI & ACCESSIBILITY": "2026 / 人工智能与无障碍",
  "PROJECT 03": "项目 03",
  "Making a phone": "让手机",
  "less confusing.": "更容易使用。",
  "A permission request, an advertisement, or a payment screen can leave an older user unsure what to do.": "权限申请、广告或支付页面，有时会让老年用户不知道该怎样操作。",
  "I designed an AI assistant that reads a screenshot, explains the page in plain language, and offers guidance suited to the situation.": "我设计了一个 AI 助手，读取截图，用通俗语言解释页面，并根据具体情况给出操作建议。",
  "OCR · Visual understanding · Workflow design": "OCR · 视觉理解 · 工作流设计",
  "A structured workflow": "有条理的工作流",
  "The design uses a 12-node workflow to recognise text and visual elements, classify the situation, and route it to the appropriate response. The output follows three parts: what the page shows, what to watch for, and a suggested next step.": "设计采用 12 个节点的工作流，识别文字和视觉元素、判断场景，再生成相应回答。输出分为三部分：页面是什么、需要注意什么、下一步可以怎么做。",
  "Test the difficult cases": "测试复杂场景",
  "Initial tests covered location permissions, advertisements, payments, ordinary chat, and verification-code screens. For sensitive operations, the assistant encourages pausing and checking with family or an official source.": "初步测试涵盖定位权限、广告、支付、普通聊天和验证码页面。遇到敏感操作时，助手会建议先暂停，向家人或官方渠道核实。",
  "A lesson in uncertainty": "学会表达不确定性",
  "Testing showed that responses could sound too certain. A payment page is not automatically a scam, and an ordinary-looking page is not a guarantee of safety. I want the assistant to communicate that uncertainty more carefully.": "测试发现，回答有时显得过于肯定。支付页面不一定是骗局，普通的页面也不代表绝对安全。我希望助手能更准确地表达这些不确定性。",
  "Handwritten notes and drawings from Hansheng's fruit DNA exploration": "田翰声探索水果 DNA 时的手写笔记与绘图",
  "2024 / SCIENCE": "2024 / 科学",
  "PROJECT 04": "项目 04",
  "A closer look": "走近",
  "at fruit DNA.": "水果 DNA。",
  "Questions about the differences between fruits led me to a smaller first step: learning how to extract DNA.": "对水果差异的好奇，让我从一个小问题开始：怎样提取 DNA？",
  "I explored how fruit type and the conditions of extraction affected the material I could collect, keeping notes and observing samples under a microscope.": "我探索了水果种类和提取条件对所获材料的影响，记录实验笔记，并用显微镜观察样本。",
  "Experimental design · Observation · Lab notes": "实验设计 · 观察 · 实验笔记",
  "Make the question testable": "让问题可以被检验",
  "With guidance from teachers and family, I learned to change one condition at a time. I compared different fruits, alcohol concentrations, and temperatures.": "在老师和家人的指导下，我学习了每次只改变一个条件，比较不同水果、酒精浓度和温度下的结果。",
  "Learn through observation": "在观察中学习",
  "I recorded what I saw, photographed samples, and compared changes in appearance. The project gave me a first-hand introduction to experimental work and the limits of simple measurements.": "我记录观察结果、拍摄样本照片，并比较外观变化。这个项目让我初步接触实验，也认识到简单测量方法的局限。",
  "A starting point": "一个起点",
  "This was an early learning project. It helped me practise asking a focused question, planning an experiment, and keeping a record of the process.": "这是我早期的学习项目。它让我练习提出明确的问题、规划实验，并记录过程。",
  "Robotics | Hansheng Tian": "机器人 | 田翰声",
  "01 / STAYING WITH IT": "01 / 持续投入",
  "One season.": "一个赛季，",
  "Then another.": "又一个赛季。",
  "VEX is where I keep returning: to a new challenge, another design, and another chance to improve.": "VEX 总能让我再次投入：迎接新的挑战，尝试新的设计，再向前进步一点。",
  "2024 VEX Robotics World Championship: Division 3rd Place.": "2024 年 VEX 机器人世界锦标赛：分区季军。",
  "Enlarge 2024 World Championship photo": "放大 2024 年世界锦标赛照片",
  "Hansheng holding a 2024 VEX World Championship Division 3rd Place trophy": "田翰声手持 2024 年 VEX 世界锦标赛分区季军奖杯",
  "2024 World Championship · Division 3rd Place": "2024 年世界锦标赛 · 分区季军",
  "My first World Championship": "第一次世界锦标赛",
  "My early VEX IQ journey took me to the Asia Championship in Macau and my first World Championship.": "最初的 VEX IQ 经历，带我参加了在澳门举办的亚洲锦标赛，以及我的第一次世界锦标赛。",
  "Learning to work across teams": "学习跨队合作",
  "At Worlds, we partnered with a team from Indiana and earned third place in our division. My season also lives on in a notebook of designs and changes.": "在世锦赛上，我们与来自印第安纳州的队伍合作，获得了分区第三名。那个赛季的设计和修改，也都留在了工程笔记里。",
  "Building, driving, documenting": "搭建、操控与记录",
  "Another VEX IQ season, another World Championship, and another engineering notebook. My involvement grew to include both building and driving.": "又一个 VEX IQ 赛季，又一次世界锦标赛，也多了一本工程笔记。我开始同时参与机器人的搭建和操控。",
  "Continuing the commitment": "继续坚持",
  "A fourth VEX IQ World Championship season. Each year gave me a different challenge to stay with.": "这是我的第四个 VEX IQ 世锦赛赛季。每一年，都有值得坚持完成的新挑战。",
  "A new chapter in VEX V5": "VEX V5 的新篇章",
  "I’m now exploring VEX V5 with Team 3296X, CharisMAX, carrying my experience into a new platform.": "现在，我正在 3296X 战队 CharisMAX 探索 VEX V5，把过去的经验带到新的平台上。",
  "THE COMPLETE ENGINEERING NOTEBOOKS": "完整工程笔记",
  "Every page of the process.": "过程中的每一页。",
  "Explore the original notebooks one page at a time. Open a book to turn pages, jump to a page, or enlarge it for a closer look.": "逐页阅读原始工程笔记。打开一本笔记，就能翻页、跳转页码，或放大查看细节。",
  "2023–2024 engineering notebook cover": "2023–2024 赛季工程笔记封面",
  "81 pages": "81 页",
  "Open notebook": "打开笔记",
  "2024–2025 engineering notebook cover": "2024–2025 赛季工程笔记封面",
  "40 pages": "40 页",
  "Beyond Robotics | Hansheng Tian": "机器人之外 | 田翰声",
  "04 / MORE SIDES OF ME": "04 / 更多面的我",
  "Time to": "一起",
  "move.": "动起来。",
  "Sport is a part of my life that I love. There is room for the court, the field, and a day out on the water.": "运动是我生活中热爱的一部分。球场、绿茵场，或是在水上度过的一天，都让我乐在其中。",
  "A day out on the water, paddleboarding.": "在水上玩桨板的一天。",
  "Enlarge paddleboarding photo": "放大桨板照片",
  "Paddleboarding on a lake on a sunny day": "晴天里在湖上划桨板",
  "On the water": "在水上",
  "Paddleboarding": "桨板",
  "Football with friends.": "和朋友一起踢足球。",
  "Enlarge football photo": "放大足球照片",
  "A group of friends on a football field": "朋友们在足球场上合影",
  "On the field": "在绿茵场",
  "Football": "足球",
  "Basketball and time with friends.": "和朋友一起打篮球。",
  "Enlarge basketball photo": "放大篮球照片",
  "Basketball with friends on an outdoor court": "和朋友在室外球场打篮球",
  "On the court": "在球场",
  "Basketball": "篮球",
  "ON THE WATER": "在水上",
  "Stand Up": "站立式",
  "ACA Level 1": "ACA 一级",
  "I completed the ACA Level 1: Introduction to Stand Up Paddleboarding Skills Assessment, alongside my kayaking assessment.": "除了皮划艇评估，我也完成了 ACA 一级站立式桨板入门技能评估。",
  "Issued August 25, 2023": "签发日期：2023 年 8 月 25 日",
  "American Canoe Association (ACA)": "美国皮划艇协会（ACA）",
  "View certificate (PDF, 2 pages)": "查看证书（PDF，共 2 页）",
  "ACA Level 1: Introduction to Stand Up Paddleboarding Skills Assessment · August 25, 2023": "ACA 一级站立式桨板入门技能评估 · 2023 年 8 月 25 日",
  "Enlarge ACA paddleboarding certificate": "放大 ACA 桨板证书",
  "Hansheng Tian's ACA Level 1 Introduction to Stand Up Paddleboarding Skills Assessment certificate, issued August 25, 2023": "田翰声的 ACA 一级站立式桨板入门技能评估证书，签发于 2023 年 8 月 25 日",
  "ACA certificate · Member number hidden": "ACA 证书 · 会员编号已隐藏",
  "Click to enlarge ↗": "点击放大 ↗",
  "Kayaking": "皮划艇",
  "I completed the ACA Level 1: Introduction to Kayaking Skills Assessment, adding a new skill to my time on the water.": "我完成了 ACA 一级皮划艇入门技能评估，为水上活动增添了一项新技能。",
  "ACA Level 1: Introduction to Kayaking Skills Assessment · August 25, 2023": "ACA 一级皮划艇入门技能评估 · 2023 年 8 月 25 日",
  "Enlarge ACA kayaking certificate": "放大 ACA 皮划艇证书",
  "Hansheng Tian's ACA Level 1 Introduction to Kayaking Skills Assessment certificate, issued August 25, 2023": "田翰声的 ACA 一级皮划艇入门技能评估证书，签发于 2023 年 8 月 25 日",
  "AT THE BOARD": "在棋盘前",
  "Go": "围棋",
  "Amateur 2 Dan": "业余二段",
  "I earned an amateur 2-dan rank in Go following the 2024 Dongcheng District “Longtan Cup” ranking tournament in Beijing.": "参加 2024 年北京市东城区“龙潭杯”围棋段位赛后，我获得了围棋业余二段称号。",
  "Certified September 27, 2024": "发证日期：2024 年 9 月 27 日",
  "Beijing Go Association & Beijing Qiyuan": "北京市围棋协会 · 北京棋院",
  "Amateur Go 2 Dan · September 27, 2024. Personal identifiers hidden for privacy.": "围棋业余二段 · 2024 年 9 月 27 日。个人证件信息已隐藏。",
  "Enlarge Go 2-dan certificate": "放大围棋二段证书",
  "Hansheng Tian's Beijing amateur Go 2-dan certificate, issued September 27, 2024, with personal identifiers hidden": "田翰声的北京市业余围棋二段证书，发证于 2024 年 9 月 27 日，个人证件信息已隐藏",
  "Go 2-dan certificate": "围棋二段证书",
  "A classroom magic performance": "在课堂上表演魔术",
  "A DIFFERENT KIND OF SURPRISE": "不一样的惊喜",
  "A little magic.": "一点小魔术。",
  "I also enjoy performing magic at school. It is another side of my curiosity, and a chance to share something unexpected.": "我也喜欢在学校表演魔术。这是我好奇心的另一面，也让我有机会给大家带来意想不到的惊喜。",
  "Hansheng working with an instructor on a robot during a summer camp": "田翰声在夏令营中与老师一起调试机器人",
  "LEARNING IN NEW PLACES": "在新的地方学习",
  "Robotics summer camp.": "机器人夏令营。",
  "A Carnegie Mellon robotics summer camp gave me another setting in which to explore my interest and learn with others.": "卡内基梅隆机器人的夏令营经历，让我在新的环境里探索兴趣，与他人共同学习。"
};
  let language = 'en';
  try { language = localStorage.getItem('hansheng-language') === 'zh' ? 'zh' : 'en'; } catch {}
  const translate = text => language === 'zh' ? (translations[text] ?? text) : text;
  const homeHeading = document.querySelector('.home-cover h1');
  const homeMarkup = homeHeading?.innerHTML;
  const textNodes = [];
  const walker = document.createTreeWalker(document.documentElement, NodeFilter.SHOW_TEXT);
  while (walker.nextNode()) {
    const node = walker.currentNode;
    if (node.parentElement?.closest('script, style, [data-language-toggle]') || homeHeading?.contains(node)) continue;
    if (translations[node.nodeValue.trim()]) textNodes.push([node, node.nodeValue]);
  }
  const attributes = [];
  document.querySelectorAll('[alt], [aria-label], [data-caption], meta[name="description"]').forEach(element => {
    for (const name of ['alt', 'aria-label', 'data-caption', 'content']) {
      const original = element.getAttribute(name);
      if (original && translations[original]) attributes.push([element, name, original]);
    }
  });
  const toggle = document.querySelector('[data-language-toggle]');
  function setLanguage(next, remember = true) {
    language = next === 'zh' ? 'zh' : 'en';
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en';
    textNodes.forEach(([node, original]) => {
      if (node.isConnected) node.nodeValue = language === 'zh' ? original.replace(original.trim(), translate(original.trim())) : original;
    });
    attributes.forEach(([element, name, original]) => element.setAttribute(name, translate(original)));
    if (homeHeading) homeHeading.innerHTML = language === 'zh' ? '田翰声' : homeMarkup;
    toggle.textContent = language === 'zh' ? 'English' : '中文';
    toggle.lang = language === 'zh' ? 'en' : 'zh-CN';
    toggle.setAttribute('aria-label', language === 'zh' ? 'Switch to English' : '切换到中文');
    if (remember) { try { localStorage.setItem('hansheng-language', language); } catch {} }
    document.dispatchEvent(new CustomEvent('languagechange', {detail: {language}}));
  }
  window.SiteI18n = {get language() {return language;}, t: translate, setLanguage};
  toggle.addEventListener('click', () => setLanguage(language === 'en' ? 'zh' : 'en'));
  setLanguage(language, false);
})();
